# Extra UI strings harvested from remaining SwiftUI/AppKit surfaces.
# Loaded by generate_xcstrings.py via add().

def register(add):
    rows = [
        ("Pan", "平移", "平移", "パン", "이동"),
        ("Hardness", "硬度", "硬度", "硬さ", "경도"),
        ("Aligned", "对齐", "對齊", "整列", "정렬"),
        ("All Layers", "所有图层", "所有圖層", "すべてのレイヤー", "모든 레이어"),
        ("This Layer", "当前图层", "目前圖層", "このレイヤー", "이 레이어"),
        ("Anchor", "锚点", "錨點", "アンカー", "기준점"),
        ("Anti-alias", "抗锯齿", "反鋸齒", "アンチエイリアス", "앤티앨리어스"),
        ("Apply Crop", "应用裁剪", "套用裁切", "切り抜きを適用", "자르기 적용"),
        ("Apply outside this range instead", "改为应用到此范围之外", "改為套用到此範圍之外", "この範囲の外側に適用", "이 범위 바깥에 적용"),
        ("Auto", "自动", "自動", "自動", "자동"),
        ("Auto Select", "自动选择", "自動選取", "自動選択", "자동 선택"),
        ("Background for transparency", "透明区域背景", "透明區域背景", "透明部分の背景", "투명 영역 배경"),
        ("Basic is quick; Advanced refines the mask against the layer's own detail, for hair and fur",
         "“基本”更快；“高级”会按图层细节修蒙版，适合头发和皮毛。",
         "「基本」更快；「進階」會依圖層細節修遮罩，適合頭髮和毛皮。",
         "「基本」は高速。「詳細」はレイヤーの輪郭でマスクを整え、髪や毛皮向きです。",
         "기본은 빠르고, 고급은 레이어 디테일로 마스크를 다듬어 머리카락·털에 적합합니다."),
        ("Black · Hide", "黑色 · 隐藏", "黑色 · 隱藏", "黒 · 隠す", "검정 · 숨기기"),
        ("White · Reveal", "白色 · 显示", "白色 · 顯示", "白 · 表示", "흰색 · 표시"),
        ("Blend", "混合", "混合", "描画", "혼합"),
        ("Canvas extension", "画布扩展", "畫布延伸", "キャンバス拡張", "캔버스 확장"),
        ("Channel", "通道", "通道", "チャンネル", "채널"),
        ("Clear the haze that leaves background showing through thin areas",
         "清除薄处透出背景的灰雾",
         "清除薄處透出背景的灰霧",
         "薄い部分から背景が透ける霞を取り除きます",
         "얇은 부분으로 배경이 비치는 흐림을 지웁니다"),
        ("Click the canvas to sample", "单击画布取样", "按一下畫布取樣", "キャンバスをクリックしてサンプル", "캔버스를 클릭해 샘플"),
        ("Click to add a point. Drag to adjust.", "单击加点，拖动调整。", "按一下加點，拖曳調整。", "クリックで点を追加、ドラッグで調整。", "클릭해 점을 추가하고 드래그로 조정하세요."),
        ("Colors", "颜色", "顏色", "カラー", "색상"),
        ("Contiguous", "连续", "連續", "隣接", "연속"),
        ("Copy Layer Mask", "拷贝图层蒙版", "拷貝圖層遮罩", "レイヤーマスクをコピー", "레이어 마스크 복사"),
        ("Copy Layers from Project", "从项目拷贝图层", "從專案拷貝圖層", "プロジェクトからレイヤーをコピー", "프로젝트에서 레이어 복사"),
        ("Copy from the active layer only, or from every visible layer as shown",
         "仅从当前图层拷贝，或从所有可见图层（所见即所得）",
         "僅從目前圖層拷貝，或從所有可見圖層（所見即所得）",
         "アクティブレイヤーだけ、または表示どおり全可視レイヤーからコピー",
         "현재 레이어만, 또는 보이는 모든 레이어에서 복사"),
        ("Couldn’t change canvas size", "无法更改画布大小", "無法變更畫布大小", "キャンバスサイズを変更できませんでした", "캔버스 크기를 바꿀 수 없음"),
        ("Couldn’t export JPEG", "无法导出 JPEG", "無法匯出 JPEG", "JPEGを書き出せませんでした", "JPEG를 내보낼 수 없음"),
        ("Couldn’t export PNG", "无法导出 PNG", "無法匯出 PNG", "PNGを書き出せませんでした", "PNG를 내보낼 수 없음"),
        ("Couldn’t open the project", "无法打开项目", "無法開啟專案", "プロジェクトを開けませんでした", "프로젝트를 열 수 없음"),
        ("Couldn’t resize the image", "无法缩放图像", "無法縮放影像", "画像をリサイズできませんでした", "이미지 크기를 바꿀 수 없음"),
        ("Couldn’t save the project", "无法保存项目", "無法儲存專案", "プロジェクトを保存できませんでした", "프로젝트를 저장할 수 없음"),
        ("Crop", "裁剪", "裁切", "切り抜き", "자르기"),
        ("Default colors", "默认颜色", "預設顏色", "デフォルトカラー", "기본 색"),
        ("Default colors (D)", "默认颜色 (D)", "預設顏色 (D)", "デフォルトカラー (D)", "기본 색 (D)"),
        ("Disable Layer Mask", "停用图层蒙版", "停用圖層遮罩", "レイヤーマスクを無効", "레이어 마스크 사용 안 함"),
        ("Distort", "扭曲", "扭曲", "歪曲", "왜곡"),
        ("Distort Layer Mask", "扭曲图层蒙版", "扭曲圖層遮罩", "レイヤーマスクを歪曲", "레이어 마스크 왜곡"),
        ("Distribution", "分布", "分布", "分布", "분포"),
        ("Drag to resize the panel", "拖动以调整面板大小", "拖曳以調整面板大小", "ドラッグしてパネルサイズを変更", "드래그하여 패널 크기 조절"),
        ("Drop into new canvas", "放到新画布", "放到新畫布", "新規キャンバスへドロップ", "새 캔버스에 놓기"),
        ("Drop to open in a new canvas", "放到此处在新画布打开", "放到此處在新畫布開啟", "ドロップして新規キャンバスで開く", "놓으면 새 캔버스에서 열림"),
        ("Duplicate Layers", "复制图层", "複製圖層", "レイヤーを複製", "레이어 복제"),
        ("Empty selection", "空选区", "空選取範圍", "空の選択範囲", "빈 선택"),
        ("Export…", "导出…", "匯出…", "書き出す…", "보내기…"),
        ("Export PNG", "导出 PNG", "匯出 PNG", "PNGを書き出す", "PNG보내기"),
        ("Extension color", "扩展颜色", "延伸顏色", "拡張色", "확장 색"),
        ("Fill", "填充", "填滿", "塗りつぶし", "채우기"),
        ("Fill the selection using surrounding pixels from this layer.",
         "用本图层周围像素填充选区。",
         "用本圖層周圍像素填滿選取範圍。",
         "このレイヤーの周囲ピクセルで選択範囲を塗りつぶします。",
         "이 레이어의 주변 픽셀로 선택 영역을 채웁니다."),
        ("Final dimensions must be 1–30,000 pixels per side.",
         "最终尺寸每边必须为 1–30,000 像素。",
         "最終尺寸每邊必須為 1–30,000 像素。",
         "最終サイズは各辺 1〜30,000 ピクセルである必要があります。",
         "최종 크기는 각 변이 1–30,000픽셀이어야 합니다."),
        ("Flip Horizontal", "水平翻转", "水平翻轉", "水平方向に反転", "가로 뒤집기"),
        ("Foreground color", "前景色", "前景色", "描画色", "전경색"),
        ("Gradient", "渐变", "漸層", "グラデーション", "그라디언트"),
        ("Group Layers", "编组图层", "群組圖層", "レイヤーをグループ化", "레이어 그룹화"),
        ("Hex", "十六进制", "十六進位", "16進数", "16진수"),
        ("Hex color", "十六进制颜色", "十六進位顏色", "16進カラー", "16진 색"),
        ("Hide the background behind a layer mask, keeping the foreground subjects. The pixels stay, so the background can be painted back at any time.",
         "用图层蒙版隐藏背景、保留前景。像素仍在，随时可以画回背景。",
         "用圖層遮罩隱藏背景、保留前景。像素仍在，隨時可以畫回背景。",
         "レイヤーマスクで背景を隠し、前景を残します。ピクセルは残るので、いつでも背景を描けます。",
         "레이어 마스크로 배경을 숨기고 전경을 남깁니다. 픽셀은 남아 언제든 배경을 다시 칠할 수 있습니다."),
        ("Hold Shift to add or Option to subtract for one outline",
         "按住 Shift 添加，或按住 Option 从当前轮廓中减去",
         "按住 Shift 加入，或按住 Option 從目前輪廓減去",
         "Shiftで追加、Optionで今の輪郭から減算",
         "Shift는 추가, Option은 현재 윤곽에서 빼기"),
        ("How far each color channel (0–255) can differ from the clicked color and still be selected",
         "每个颜色通道（0–255）与单击颜色的允许偏差",
         "每個顏色通道（0–255）與點選顏色的允許偏差",
         "クリック色との各チャンネル許容差（0–255）",
         "클릭한 색과 각 채널(0–255)의 허용 차이"),
        ("Import Image", "导入图像", "匯入影像", "画像を読み込む", "이미지 가져오기"),
        ("Import Images", "导入图像", "匯入影像", "画像を読み込む", "이미지 가져오기"),
        ("Keep the source moving with the brush between strokes; off starts every stroke at the source point",
         "开启后源点随笔刷移动；关闭则每笔都从源点开始",
         "開啟後來源隨筆刷移動；關閉則每筆都從來源開始",
         "オンでソースがブラシと一緒に移動。オフは各ストロークをソース位置から開始",
         "켜면 소스가 브러시와 함께 움직이고, 끄면 매 획이 소스에서 시작됩니다"),
        ("Keeps this point fixed. Artwork is not scaled; cropped content remains outside the canvas.",
         "固定此点。图像不缩放；裁掉的内容仍在画布外。",
         "固定此點。影像不縮放；裁掉的內容仍在畫布外。",
         "この点を固定します。拡大縮小せず、はみ出した内容はキャンバス外に残ります。",
         "이 점을 고정합니다. 크기는 바꾸지 않으며 잘린 내용은 캔버스 밖에 남습니다."),
        ("Lasso", "套索", "套索", "なげなわ", "올가미"),
        ("Layer Blend Mode", "图层混合模式", "圖層混合模式", "レイヤー描画モード", "레이어 혼합 모드"),
        ("Layer Opacity", "图层不透明度", "圖層不透明度", "レイヤー不透明度", "레이어 불투명도"),
        ("Layer Mask", "图层蒙版", "圖層遮罩", "レイヤーマスク", "레이어 마스크"),
        ("Layers", "图层", "圖層", "レイヤー", "레이어"),
        ("Linear histogram with automatic vertical scaling. Tall spikes may extend beyond the graph; all tones from 0 to 255 remain included.",
         "线性直方图，纵向自动缩放。尖峰可能超出图外，0 到 255 的色调仍全部计入。",
         "線性直方圖，縱向自動縮放。尖峰可能超出圖外，0 到 255 的色調仍全部計入。",
         "縦方向を自動スケールする線形ヒストグラム。高いピークは枠外に出ても、0〜255のトーンはすべて含まれます。",
         "세로가 자동 조절되는 선형 히스토그램입니다. 높은 봉우리는 그래프 밖으로 나갈 수 있지만 0–255 톤은 모두 포함됩니다."),
        ("Linear runs along the line; Radial spreads out from the start point",
         "线性沿拖动线；径向从起点向外扩散",
         "線性沿拖曳線；徑向從起點向外擴散",
         "線形は線に沿う。円形は始点から広がる",
         "선형은 선을 따르고, 원형은 시작점에서 퍼집니다"),
        ("Liquify pushes pixels · Blur softens · Smudge drags color along",
         "液化推移像素 · 模糊柔化 · 涂抹拖动颜色",
         "液化推移像素 · 模糊柔化 · 塗抹拖動顏色",
         "液化はピクセルを押す · ぼかしは柔らかく · 指先は色を引きずる",
         "액화는 픽셀을 밀고 · 흐림은 부드럽게 · 문지르기는 색을 끕니다"),
        ("Loading histogram…", "正在加载直方图…", "正在載入直方圖…", "ヒストグラムを読み込み中…", "히스토그램 불러오는 중…"),
        ("Lock aspect ratio", "锁定长宽比", "鎖定長寬比", "縦横比を固定", "가로세로비 잠금"),
        ("Mask", "蒙版", "遮罩", "マスク", "마스크"),
        ("Match the clicked pixel, or the average of the pixels around it",
         "匹配单击像素，或其周围像素的平均值",
         "符合點選像素，或其周圍像素的平均值",
         "クリックしたピクセル、または周囲の平均に一致",
         "클릭한 픽셀 또는 주변 평균에 맞춥니다"),
        ("Mode", "模式", "模式", "モード", "모드"),
        ("Move Layer", "移动图层", "移動圖層", "レイヤーを移動", "레이어 이동"),
        ("Move Layers", "移动图层", "移動圖層", "レイヤーを移動", "레이어 이동"),
        ("Move Selection", "移动选区", "移動選取範圍", "選択範囲を移動", "선택 영역 이동"),
        ("New Canvas", "新建画布", "新增畫布", "新規キャンバス", "새 캔버스"),
        ("New Folder", "新建文件夹", "新增檔案夾", "新規フォルダ", "새 폴더"),
        ("New color", "新颜色", "新顏色", "新しい色", "새 색"),
        ("No layers yet", "还没有图层", "還沒有圖層", "レイヤーはまだありません", "아직 레이어가 없습니다"),
        ("Only print dimensions and resolution change. Pixels stay unchanged.",
         "只改变打印尺寸和分辨率，像素不变。",
         "只改變列印尺寸和解析度，像素不變。",
         "印刷サイズと解像度だけが変わり、ピクセルは変わりません。",
         "인쇄 크기와 해상도만 바뀌고 픽셀은 그대로입니다."),
        ("Opacity percent", "不透明度百分比", "不透明度百分比", "不透明度パーセント", "불투명도 퍼센트"),
        ("Open one project at a time", "一次打开一个项目", "一次開啟一個專案", "一度に1つのプロジェクト", "한 번에 프로젝트 하나"),
        ("Open Project", "打开项目", "開啟專案", "プロジェクトを開く", "프로젝트 열기"),
        ("Option-click to set the source", "Option-单击设源", "Option-點一下設來源", "Optionクリックでソース指定", "Option-클릭으로 소스 지정"),
        ("Paint Mask", "绘制蒙版", "繪製遮罩", "マスクをペイント", "마스크 칠하기"),
        ("Paint with the foreground color (B), or erase pixels away (E)",
         "用前景色绘制 (B)，或擦除像素 (E)",
         "用前景色繪製 (B)，或擦除像素 (E)",
         "描画色で塗る (B)、またはピクセルを消す (E)",
         "전경색으로 칠하거나 (B) 픽셀을 지웁니다 (E)"),
        ("Positive straightens lines that bow outward (barrel); negative, lines that bow inward (pincushion).",
         "正值拉直向外弯的桶形线；负值拉直向内弯的枕形线。",
         "正值拉直向外彎的桶形線；負值拉直向內彎的枕形線。",
         "正は外に膨らむ樽型、負は内にへこむ糸巻き型を矯正します。",
         "양수는 바깥으로 휜 배럴을, 음수는 안쪽으로 휜 핀쿠션을 펴줍니다."),
        ("Press 1–9 for 10–90%, 0 for 100%", "按 1–9 设为 10–90%，0 为 100%", "按 1–9 設為 10–90%，0 為 100%", "1–9で10–90%、0で100%", "1–9는 10–90%, 0은 100%"),
        ("Press L to switch between Freehand and Polygonal", "按 L 在自由和多边形之间切换", "按 L 在自由和多邊形之間切換", "Lでフリーハンドと多角形を切替", "L로 자유/다각형 전환"),
        ("Press M to switch between Rectangle and Ellipse", "按 M 在矩形和椭圆之间切换", "按 M 在矩形和橢圓之間切換", "Mで矩形と楕円を切替", "M으로 사각형/타원 전환"),
        ("Project tabs", "项目标签", "專案分頁", "プロジェクトタブ", "프로젝트 탭"),
        ("Pull the mask onto the image's own edges, which recovers hair and fur",
         "把蒙版拉到图像自身边缘，以找回头发和皮毛",
         "把遮罩拉到影像自身邊緣，以找回頭髮和毛皮",
         "マスクを画像自身のエッジへ寄せ、髪や毛皮を復元",
         "마스크를 이미지 가장자리로 당겨 머리카락·털을 살립니다"),
        ("Range", "范围", "範圍", "範囲", "범위"),
        ("Ratio", "比例", "比例", "比率", "비율"),
        ("Read colors from the active layer only, or from every visible layer as shown",
         "仅从当前图层读色，或从所有可见图层（所见即所得）",
         "僅從目前圖層讀色，或從所有可見圖層（所見即所得）",
         "アクティブレイヤーだけ、または表示どおり全可視レイヤーから色を読む",
         "현재 레이어만, 또는 보이는 모든 레이어에서 색을 읽습니다"),
        ("Remove point", "删除锚点", "刪除錨點", "ポイントを削除", "점 삭제"),
        ("Rename Layer", "重命名图层", "重新命名圖層", "レイヤー名を変更", "레이어 이름 변경"),
        ("Rename…", "重命名…", "重新命名…", "名前を変更…", "이름 변경…"),
        ("Reorder Layers", "重排图层", "重排圖層", "レイヤーを並べ替え", "레이어 재정렬"),
        ("Resample", "重新采样", "重新取樣", "再サンプル", "다시 샘플"),
        ("Reset curve", "重置曲线", "重設曲線", "カーブをリセット", "곡선 재설정"),
        ("Resize", "缩放", "縮放", "リサイズ", "크기 조정"),
        ("Resizes layer pixels and applies existing transforms. Undo restores the originals.",
         "缩放图层像素并应用已有变换。撤销可恢复原图。",
         "縮放圖層像素並套用既有變形。復原可恢復原圖。",
         "レイヤーのピクセルをリサイズし、既存の変形を適用します。取り消しで元に戻せます。",
         "레이어 픽셀을 리사이즈하고 기존 변형을 적용합니다. 실행 취소하면 원본으로 돌아갑니다."),
        ("Resolution", "分辨率", "解析度", "解像度", "해상도"),
        ("Reverse", "反向", "反向", "反転", "반전"),
        ("Round the rectangle's corners by this many pixels; 0 keeps them square",
         "按此像素数圆角；0 保持直角",
         "按此像素數圓角；0 保持直角",
         "このピクセル数で角を丸める。0は直角のまま",
         "이 픽셀만큼 모서리를 둥글게 합니다. 0이면 직각"),
        ("Sample", "取样", "取樣", "サンプル", "샘플"),
        ("Sample Size", "取样大小", "取樣大小", "サンプルサイズ", "샘플 크기"),
        ("Sampling", "采样", "取樣", "サンプリング", "샘플링"),
        ("Saturation and brightness", "饱和度与亮度", "飽和度與亮度", "彩度と明るさ", "채도와 밝기"),
        ("Scale width and height together, about the center",
         "以中心同时缩放宽高",
         "以中心同時縮放寬高",
         "中心を基準に幅と高さを同時にスケール",
         "중심을 기준으로 너비와 높이를 함께 조절"),
        ("Select layers by clicking the canvas. When off, hold Command to select a layer.",
         "单击画布选择图层。关闭时按住 Command 再选。",
         "按一下畫布選取圖層。關閉時按住 Command 再選。",
         "キャンバスをクリックしてレイヤーを選択。オフのときはCommandを押しながら。",
         "캔버스를 클릭해 레이어를 선택합니다. 끄면 Command를 누른 채 선택하세요."),
        ("Select only similar pixels connected to the one you click; off selects them everywhere",
         "只选与单击点相连的相似像素；关闭则全图选取",
         "只選與點選點相連的相似像素；關閉則全圖選取",
         "クリック地点につながる近似ピクセルだけ。オフなら画面全体",
         "클릭한 곳과 이어진 비슷한 픽셀만 선택합니다. 끄면 전체에서 선택합니다"),
        ("Shape", "形状", "形狀", "シェイプ", "도형"),
        ("Shapes fill with the foreground color; click to change it",
         "形状用前景色填充；单击可更改",
         "形狀用前景色填滿；按一下可變更",
         "シェイプは描画色で塗られます。クリックで変更",
         "도형은 전경색으로 채워집니다. 클릭해 바꾸세요"),
        ("Shift-U switches between Rectangle and Ellipse", "Shift-U 在矩形和椭圆之间切换", "Shift-U 在矩形和橢圓之間切換", "Shift-Uで矩形と楕円を切替", "Shift-U로 사각형/타원 전환"),
        ("Show the transform box and handles (⌘H). When hidden, drag anywhere to move the layer.",
         "显示变换框和手柄（⌘H）。隐藏时可在任意处拖动图层。",
         "顯示變形框和手柄（⌘H）。隱藏時可在任意處拖曳圖層。",
         "変形枠とハンドルを表示（⌘H）。非表示時はどこでもドラッグして移動。",
         "변형 상자와 핸들을 표시합니다(⌘H). 숨기면 아무 곳이나 드래그해 레이어를 옮깁니다."),
        ("Shrink the mask to drop the rim of background color around the subject, or grow it",
         "收缩蒙版去掉主体周围的背景边，或向外扩展",
         "收縮遮罩去掉主體周圍的背景邊，或向外擴展",
         "マスクを縮めて被写体周囲の背景縁を落とす、または広げる",
         "마스크를 줄여 피사체 주변 배경 테두리를 없애거나, 키울 수 있습니다"),
        ("Smooth selection edges; turn off for hard pixel edges",
         "平滑选区边缘；关闭则为硬像素边",
         "平滑選取邊緣；關閉則為硬像素邊",
         "選択の縁を滑らかに。オフで硬いピクセル端",
         "선택 가장자리를 부드럽게 합니다. 끄면 단단한 픽셀 가장자리"),
        ("Swap colors", "交换颜色", "交換顏色", "カラーを交換", "색 바꾸기"),
        ("Swap foreground and background (X)", "交换前景与背景 (X)", "交換前景與背景 (X)", "描画色と背景色を交換 (X)", "전경/배경 바꾸기 (X)"),
        ("Targeted adjustment", "定向调整", "定向調整", "対象調整", "대상 조정"),
        ("Targeted adjustment: drag on the image to change that color's saturation, or its hue with Command held",
         "定向调整：在图像上拖动可改该颜色饱和度，按住 Command 则改色相",
         "定向調整：在影像上拖曳可改該顏色飽和度，按住 Command 則改色相",
         "対象調整：画像上をドラッグでその色の彩度、Command押しながらで色相",
         "대상 조정: 이미지에서 드래그하면 그 색의 채도, Command를 누르면 색조가 바뀝니다"),
        ("Tolerance", "容差", "容差", "許容値", "허용치"),
        ("Transform Layer Mask", "变换图层蒙版", "變形圖層遮罩", "レイヤーマスクを変形", "레이어 마스크 변형"),
        ("Transform Layers", "变换图层", "變形圖層", "レイヤーを変形", "레이어 변형"),
        ("Type", "类型", "類型", "種類", "유형"),
        ("Unlink Layer Mask", "取消链接图层蒙版", "取消連結圖層遮罩", "レイヤーマスクのリンク解除", "레이어 마스크 링크 해제"),
        ("Unsaved changes", "未保存的更改", "未儲存的變更", "未保存の変更", "저장하지 않은 변경"),
        ("Updating preview…", "正在更新预览…", "正在更新預覽…", "プレビューを更新中…", "미리보기 업데이트 중…"),
        ("Zoom", "缩放", "縮放", "ズーム", "확대/축소"),
        ("Zoom percentage", "缩放百分比", "縮放百分比", "ズームパーセント", "확대/축소 퍼센트"),
        ("Zoom percentage (0.1–3200%). Press Return to apply.",
         "缩放百分比（0.1–3200%）。按 Return 应用。",
         "縮放百分比（0.1–3200%）。按 Return 套用。",
         "ズーム（0.1–3200%）。Returnで適用。",
         "확대/축소(0.1–3200%). Return으로 적용."),
        ("pixels/inch", "像素/英寸", "像素/英吋", "ピクセル/インチ", "픽셀/인치"),
        ("· encoded preview, fitted to window", "· 编码预览，适合窗口", "· 編碼預覽，符合視窗", "· エンコード済みプレビュー（ウィンドウに合わせる）", "· 인코딩 미리보기, 창에 맞춤"),
        ("Save Project", "保存项目", "儲存專案", "プロジェクトを保存", "프로젝트 저장"),
        ("Save Project As", "项目另存为", "專案另存新檔", "名前を付けてプロジェクトを保存", "프로젝트를 다른 이름으로 저장"),
        ("Don’t Save", "不保存", "不儲存", "保存しない", "저장 안 함"),
        ("Save changes to %@?", "要保存对 %@ 的更改吗？", "要儲存對 %@ 的變更嗎？", "%@への変更を保存しますか？", "%@의 변경 사항을 저장할까요?"),
        ("Your changes will be lost if you don’t save them.",
         "如果不保存，更改将丢失。",
         "如果不儲存，變更將遺失。",
         "保存しないと変更は失われます。",
         "저장하지 않으면 변경 내용이 사라집니다."),
        ("Hide/Show Layer", "隐藏/显示图层", "隱藏/顯示圖層", "レイヤーを表示/隠す", "레이어 숨기기/보기"),
        ("Add White Mask", "添加白色蒙版", "加入白色遮罩", "白マスクを追加", "흰색 마스크 추가"),
        ("Add Black Mask", "添加黑色蒙版", "加入黑色遮罩", "黒マスクを追加", "검정 마스크 추가"),
        ("Add layer mask", "添加图层蒙版", "加入圖層遮罩", "レイヤーマスクを追加", "레이어 마스크 추가"),
        ("Add layer mask (the selection becomes black)", "添加图层蒙版（选区变为黑色）", "加入圖層遮罩（選取範圍變為黑色）", "レイヤーマスクを追加（選択は黒）", "레이어 마스크 추가(선택은 검정)"),
        ("Add Mask from Selection", "从选区添加蒙版", "從選取範圍加入遮罩", "選択からマスクを追加", "선택에서 마스크 추가"),
        ("Add Reveal-All Mask", "添加全显蒙版", "加入全顯遮罩", "すべて表示のマスクを追加", "모두 표시 마스크 추가"),
        ("Expand or collapse folder", "展开或折叠文件夹", "展開或收合檔案夾", "フォルダを開閉", "폴더 펼치기/접기"),
        ("Link layer and mask so they move together", "链接图层与蒙版，使其一起移动", "連結圖層與遮罩，使其一起移動", "レイヤーとマスクをリンクして一緒に動かす", "레이어와 마스크를 연결해 함께 움직입니다"),
        ("Unlink layer and mask to move or transform them separately",
         "取消链接，以便分别移动或变换",
         "取消連結，以便分別移動或變形",
         "リンクを外して別々に移動・変形",
         "링크를 해제해 따로 이동하거나 변형합니다"),
        ("Select image pixels", "选择图像像素", "選取影像像素", "画像ピクセルを選択", "이미지 픽셀 선택"),
        ("Select layer mask; Shift-click to enable/disable; Cmd-click to select its black areas (Cmd-Shift adds, Cmd-Option subtracts)",
         "选择图层蒙版；Shift-单击启用/停用；⌘-单击选黑色区域（⌘⇧ 添加，⌘⌥ 减去）",
         "選取圖層遮罩；Shift-點一下啟用/停用；⌘-點一下選黑色區域（⌘⇧ 加入，⌘⌥ 減去）",
         "レイヤーマスクを選択。Shiftクリックで有効/無効。⌘クリックで黒領域を選択（⌘⇧追加、⌘⌥減算）",
         "레이어 마스크를 선택합니다. Shift-클릭은 사용/중지, ⌘-클릭은 검정 영역 선택(⌘⇧ 추가, ⌘⌥ 빼기)"),
        ("Adjustment · Double-click to edit", "调整 · 双击编辑", "調整 · 按兩下編輯", "調整 · ダブルクリックで編集", "조정 · 더블클릭하여 편집"),
        ("Folder", "文件夹", "檔案夾", "フォルダ", "폴더"),
        ("Missing source", "缺少源图层", "缺少來源圖層", "ソースがありません", "소스 없음"),
        ("Clipped to %@", "剪贴到 %@", "剪裁到 %@", "%@にクリップ", "%@에 클립"),
        ("Clipping mask based on %@. Option-click the bottom of its row to release.",
         "基于 %@ 的剪贴蒙版。Option-单击该行底部可释放。",
         "基於 %@ 的剪裁遮罩。Option-點一下該列底部可釋放。",
         "%@に基づくクリッピングマスク。行の下端をOptionクリックで解除。",
         "%@ 기반 클리핑 마스크. 행 하단을 Option-클릭하면 해제됩니다."),
        ("Link mask: %@", "链接蒙版：%@", "連結遮罩：%@", "マスクをリンク: %@", "마스크 연결: %@"),
        ("Unlink mask: %@", "取消链接蒙版：%@", "取消連結遮罩：%@", "マスクのリンク解除: %@", "마스크 연결 해제: %@"),
        ("Select image: %@", "选择图像：%@", "選取影像：%@", "画像を選択: %@", "이미지 선택: %@"),
        ("Select mask: %@", "选择蒙版：%@", "選取遮罩：%@", "マスクを選択: %@", "마스크 선택: %@"),
        ("Hide %@", "隐藏 %@", "隱藏 %@", "%@を隠す", "%@ 숨기기"),
        ("Show %@", "显示 %@", "顯示 %@", "%@を表示", "%@ 보기"),
        ("Layer %d", "图层 %d", "圖層 %d", "レイヤー %d", "레이어 %d"),
        ("Folder %d", "文件夹 %d", "檔案夾 %d", "フォルダ %d", "폴더 %d"),
        ("New %@ Adjustment", "新建%@调整", "新增%@調整", "新規%@調整", "새 %@ 조정"),
        ("Edit %@ Adjustment", "编辑%@调整", "編輯%@調整", "%@調整を編集", "%@ 조정 편집"),
        ("Current: %d × %d pixels", "当前：%d × %d 像素", "目前：%d × %d 像素", "現在: %d × %dピクセル", "현재: %d × %d픽셀"),
        ("%d × %d px", "%d × %d 像素", "%d × %d 像素", "%d × %d px", "%d × %d px"),
        ("%d × %d px · sRGB", "%d × %d 像素 · sRGB", "%d × %d 像素 · sRGB", "%d × %d px · sRGB", "%d × %d px · sRGB"),
        ("%d × %d pixels", "%d × %d 像素", "%d × %d 像素", "%d × %dピクセル", "%d × %d픽셀"),
        ("New: %d × %d pixels · %@ uncompressed", "新建：%d × %d 像素 · %@ 未压缩", "新增：%d × %d 像素 · %@ 未壓縮", "新規: %d × %dピクセル · 非圧縮%@", "새로: %d × %d픽셀 · 비압축 %@"),
        ("%@ uncompressed RGBA canvas", "%@ 未压缩 RGBA 画布", "%@ 未壓縮 RGBA 畫布", "非圧縮RGBAキャンバス %@", "비압축 RGBA 캔버스 %@"),
        ("Result: %d × %d pixels", "结果：%d × %d 像素", "結果：%d × %d 像素", "結果: %d × %dピクセル", "결과: %d × %d픽셀"),
        ("Use 1–30,000 pixels per side, up to 100 megapixels, and 1–9,600 pixels/inch.",
         "每边 1–30,000 像素，最多 1 亿像素，分辨率 1–9,600 像素/英寸。",
         "每邊 1–30,000 像素，最多 1 億像素，解析度 1–9,600 像素/英吋。",
         "各辺 1〜30,000 ピクセル、最大 1億ピクセル、1〜9,600 ピクセル/インチ。",
         "각 변 1–30,000픽셀, 최대 1억 픽셀, 1–9,600픽셀/인치."),
        ("Top left", "左上", "左上", "左上", "왼쪽 위"),
        ("Top center", "上中", "上中", "上中央", "위 가운데"),
        ("Top right", "右上", "右上", "右上", "오른쪽 위"),
        ("Middle left", "左中", "左中", "左中央", "왼쪽 가운데"),
        ("Center", "居中", "置中", "中央", "가운데"),
        ("Middle right", "右中", "右中", "右中央", "오른쪽 가운데"),
        ("Bottom left", "左下", "左下", "左下", "왼쪽 아래"),
        ("Bottom center", "下中", "下中", "下中央", "아래 가운데"),
        ("Bottom right", "右下", "右下", "右下", "오른쪽 아래"),
        ("Selected", "已选", "已選", "選択中", "선택됨"),
        ("Transparent", "透明", "透明", "透明", "투명"),
        ("Foreground", "前景", "前景", "描画色", "전경"),
        ("Background", "背景", "背景", "背景色", "배경"),
        ("Black", "黑色", "黑色", "黒", "검정"),
        ("White", "白色", "白色", "白", "흰색"),
        ("Custom", "自定", "自訂", "カスタム", "사용자 설정"),
        ("Color Picker (Background Color)", "拾色器（背景色）", "取色器（背景色）", "カラーピッカー（背景色）", "색 선택기(배경색)"),
        ("Color Picker (Foreground Color)", "拾色器（前景色）", "取色器（前景色）", "カラーピッカー（描画色）", "색 선택기(전경색)"),
        ("Color Picker (Gradient Map Highlights)", "拾色器（渐变映射高光）", "取色器（漸層對應高光）", "カラーピッカー（グラデーションマップハイライト）", "색 선택기(그라디언트 맵 하이라이트)"),
        ("Color Picker (Gradient Map Shadows)", "拾色器（渐变映射阴影）", "取色器（漸層對應陰影）", "カラーピッカー（グラデーションマップシャドウ）", "색 선택기(그라디언트 맵 섀도)"),
        ("This layer supplies a live mask", "此图层提供实时蒙版", "此圖層提供即時遮罩", "このレイヤーはライブマスクを供給しています", "이 레이어가 라이브 마스크를 제공합니다"),
        ("These layers supply live masks", "这些图层提供实时蒙版", "這些圖層提供即時遮罩", "これらのレイヤーはライブマスクを供給しています", "이 레이어들이 라이브 마스크를 제공합니다"),
        ("Bake keeps the current masked appearance in the dependent layers’ pixels. Remove Links reveals their pixels. You can undo either choice.",
         "“拼合并删除”把当前蒙版效果写入依赖图层。“移除链接并删除”则露出其像素。两种操作都可撤销。",
         "「拼合並刪除」把目前遮罩效果寫入依賴圖層。「移除連結並刪除」則露出其像素。兩種操作都可復原。",
         "「ベイクして削除」は現在のマスク見た目を依存レイヤーに書き込みます。「リンクを外して削除」はピクセルを露出します。どちらも取り消せます。",
         "베이크 후 삭제는 현재 마스크 모습을 종속 레이어에 굽습니다. 링크 제거 후 삭제는 픽셀을 드러냅니다. 둘 다 실행 취소할 수 있습니다."),
        ("Remove Links and Delete", "移除链接并删除", "移除連結並刪除", "リンクを外して削除", "링크 제거 후 삭제"),
        ("Magic Wand", "魔棒", "魔術棒", "自動選択", "마법봉"),
        ("Marquee", "选框", "選框", "選択範囲", "선택 윤곽"),
        ("Free", "自由", "自由", "フリー", "자유"),
        ("#", "#", "#", "#", "#"),
        ("%", "%", "%", "%", "%"),
        ("Click the original layer to set %@. Click the eyedropper again to stop.",
         "单击原图层以设置%@。再次单击吸管可停止。",
         "按一下原圖層以設定%@。再按一下滴管可停止。",
         "元のレイヤーをクリックして%@を設定。スポイトをもう一度クリックで終了。",
         "원본 레이어를 클릭해 %@을(를) 설정하세요. 스포이드를 다시 클릭하면 멈춥니다."),
        ("Input %d · Output %d", "输入 %d · 输出 %d", "輸入 %d · 輸出 %d", "入力 %d · 出力 %d", "입력 %d · 출력 %d"),
        ("Expand", "扩展", "擴展", "拡張", "확장"),
        ("Contract", "收缩", "收縮", "縮小", "축소"),
        ("%@ the selection by this many pixels", "将选区%@这么多像素", "將選取範圍%@這麼多像素", "選択範囲を%@ピクセル", "선택 영역을 %@픽셀만큼"),
    ]
    for row in rows:
        add(*row)
